remote_theme: "mmistakes/jekyll-theme-basically-basic"
title: "Super Class"
description: "Basic app to help manage a dance class"
logo: "./logo_single.png"
# show_downloads: ["true" or "false" to indicate whether to provide a download URL]
# google_analytics: 